# .goreleaser.yml
release:
  # 要release的存储库。
  # 默认值从原始远程URL中提取。
  github:
    owner: user
    name: repo

  # 如果设置为true，则不会自动发布该版本。
  # 默认值为false。
  draft: true

  # 如果设置为true，则将发布tag为 预发布版本。
  # 默认值为false。
  prerelease: true

  # 您可以更改GitHub版本的名称。
  # 默认是``
  name_template: '{{.ProjectName}}-v{{.Version}} {{.Env.USER}}'

  # 您可以禁用此管道，将不上传到GitHub
  # 默认为false。
  disable: true